import type { HotelTier } from './types'

export interface PackageCourse {
  name: string
  slug: string
  blurb: string
  images: string[]
  /** GolfNow tee-times affiliate link (where available) */
  golfNow?: string
  /** official course website — shown when a course isn't on GolfNow */
  website?: string
}

// Official course websites (fallback link for courses not on GolfNow)
const WEBSITE: Record<string, string> = {
  "pga-west-stadium": "https://www.pgawest.com/golf",
  "indian-wells-celebrity": "https://www.indianwellsgolfresort.com/",
  "desert-willow-firecliff": "https://www.desertwillow.com/",
  "indian-canyons-north": "https://www.indiancanyonsgolf.com/",
  "tahquitz-legend": "https://www.tahquitzgolfresort.com/",
  "escena": "https://escenagolf.com/golf/",
  "tiburon-gold": "https://www.tiburonnaples.com/",
  "saltleaf": "https://saltleaf.com/",
  "lely-flamingo": "https://www.lelyresortgolf.com/",
  "eagle-lakes": "https://www.eaglelakesgolfclub.net/",
  "valencia-naples": "https://www.valenciagolfandcountryclub.com/",
  "cypress-woods": "https://cypresswoodsgolf.com/",
  "pinehurst-no2": "https://www.pinehurst.com/golf/courses/no-2/",
  "tobacco-road": "https://tobaccoroadgolf.com/",
  "mid-pines": "https://midpinesinn.com/",
  "legacy-golf-links": "https://www.legacygolflinks.com/",
  "talamore": "https://www.talamore.com/",
  "longleaf": "https://www.longleafgfc.com/",
  "kiawah-ocean": "https://kiawahresort.com/golf/the-ocean-course/",
  "kiawah-turtle-point": "https://kiawahresort.com/golf/turtle-point/",
  "wild-dunes-links": "https://www.wilddunesresort.com/golf/",
  "patriots-point": "https://www.patriotspointlinks.com/",
  "rivertowne": "https://www.rivertownecountryclub.com/",
  "charleston-muni": "https://www.charleston-sc.gov/644/Golf",
  "harbour-town": "https://www.seapines.com/golf-booking#/golf/courses",
  "atlantic-dunes": "https://www.seapines.com/golf-booking#/golf/courses",
  "heron-point": "https://www.seapines.com/golf-booking#/golf/courses",
  "oyster-reef": "https://hiltonheadgolf.net/clubs/oyster-reef",
  "old-south": "https://www.oldsouthgolf.com/",
  "golden-bear": "https://www.invitedclubs.com/clubs/golden-bear-golf-club-at-indigo-run",
  "arthur-hills": "https://www.boynegolf.com/eleven-courses/arthur-hills",
  "donald-ross": "https://www.boynegolf.com/eleven-courses/donald-ross-memorial",
  "bay-harbor": "https://www.boynegolf.com/eleven-courses/links-quarry",
  "monument-boyne": "https://www.boynegolf.com/eleven-courses/the-monument",
  "dunmaglas": "https://www.dunmaglas.com/",
  "crooked-tree": "https://www.innatbayharbor.com/activities/golf/crooked-tree",
  "shadow-creek": "https://www.mgmresorts.com/en/things-to-do/shadow-creek-golf-course.html",
  "paiute": "https://www.lvpaiutegolf.com/teetimes",
  "cascata": "https://golfcascata.com/",
  "serket": "https://golfserket.com/",
  "bali-hai": "https://balihaigolfclub.com/",
  "revere-concord": "https://reveregolf.com/",
  "boulder-creek": "https://www.bouldercreekgc.com/",
  "arroyo-red-rock": "https://thearroyogolfclub.com/",
  "disney-magnolia": "https://www.golfwdw.com/courses/disneys-magnolia-golf-course",
  "waldorf-astoria": "https://www.waldorfastoriaorlando.com/golf/golf-club/",
  "crooked-cat": "https://www.ocngolf.com/crooked-cat/",
  "shingle-creek": "https://www.shinglecreekgolf.com/",
  "panther-lake": "https://www.ocngolf.com/",
  "disney-palm": "https://www.golfwdw.com/courses/disneys-palm-golf-course",
  "aviara": "https://parkhyattaviara.com/golf/",
  "maderas": "https://www.maderasgolf.com/",
  "torrey-pines": "https://www.sandiego.gov/torrey-pines",
  "singing-hills": "https://www.singinghillsgolfclub.com/golf/",
  "steele-canyon": "https://www.steelecanyon.com/course-details/",
  "mt-woodson": "https://www.mtwoodsongolfclub.com/",
  wekopa: 'https://wekopa.com/',
  'troon-north': 'https://www.troonnorthgolf.com/',
  'tpc-stadium': 'https://tpc.com/scottsdale/stadium-course/',
  'tpc-champions': 'https://tpc.com/scottsdale/champions-course/',
  kierland: 'https://www.kierlandgolf.com/',
  mcdowell: 'https://arcisgolf.com/clubs/mcdowell-mountain-golf-club/golf-course',
  'tpc-myrtle': 'https://www.tpcmyrtlebeach.com/',
  caledonia: 'https://caledoniagolfandfishclub.com/',
  'barefoot-dye': 'https://barefootgolf.com/',
  'kings-north': 'https://www.myrtlebeachnational.com/about-myrtle-beach-national/',
  'world-tour': 'https://www.theworldtourgolf.com/',
  'man-o-war': 'https://www.mysticalgolf.com/',
  arrowhead: 'https://arrowheadcc.com/',
  'indigo-creek': 'https://www.indigocreekgolfclub.com/',
}

// GolfNow tee-time links per course (from the partner's package doc)
const GOLFNOW: Record<string, string> = {
  "pga-west-stadium": "https://www.golfnow.com/tee-times/facility/3155-pga-west-pete-dye-stadium-course/search",
  "indian-wells-celebrity": "https://www.golfnow.com/tee-times/facility/214-indian-wells-golf-resort-celebrity-course/search",
  "desert-willow-firecliff": "https://www.golfnow.com/tee-times/facility/208-desert-willow-golf-resort-firecliff/search",
  "indian-canyons-north": "https://www.golfnow.com/tee-times/facility/3942-indian-canyons-golf-resort-north-course/search",
  "tahquitz-legend": "https://www.golfnow.com/tee-times/facility/2930-tahquitz-creek-golf-resort-legend-course/search",
  "escena": "https://www.golfnow.com/tee-times/facility/1525-escena/search",
  "tiburon-gold": "https://www.golfnow.com/tee-times/facility/14590-tiburon-golf-club-gold-course/search",
  "saltleaf": "https://www.golfnow.com/tee-times/facility/3664-raptor-bay-golf-club/search",
  "lely-flamingo": "https://www.golfnow.com/tee-times/facility/16781-lely-resort-golf-country-club-flamingo/search",
  "eagle-lakes": "https://www.golfnow.com/tee-times/facility/5194-eagle-lakes-golf-club-naples-fl/search",
  "valencia-naples": "https://www.golfnow.com/tee-times/facility/4566-valencia-golf-and-country-club/search",
  "cypress-woods": "https://www.golfnow.com/tee-times/facility/6484-cypress-woods-golf-country-club/search",
  "tobacco-road": "https://www.golfnow.com/tee-times/facility/6022-tobacco-road-golf-course/search",
  "mid-pines": "https://www.golfnow.com/tee-times/facility/17326-mid-pines-inn-and-golf-club/search",
  "legacy-golf-links": "https://www.golfnow.com/tee-times/facility/13497-legacy-golf-links/search",
  "talamore": "https://www.golfnow.com/tee-times/facility/5597-talamore-golf-resort/search",
  "longleaf": "https://www.golfnow.com/tee-times/facility/5307-longleaf-golf-family-club/search",
  "wild-dunes-links": "https://www.golfnow.com/tee-times/facility/14228-wild-dunes-resort-links-course/search",
  "patriots-point": "https://www.golfnow.com/tee-times/facility/83-patriots-point-golf-links/search",
  "rivertowne": "https://www.golfnow.com/tee-times/facility/6843-rivertowne-country-club/search",
  "charleston-muni": "https://www.golfnow.com/tee-times/facility/6169-charleston-municipal-golf-course/search",
  "oyster-reef": "https://www.golfnow.com/tee-times/facility/13554-oyster-reef-golf-club/search",
  "old-south": "https://www.golfnow.com/tee-times/facility/6378-old-south-golf-links/search",
  "golden-bear": "https://www.golfnow.com/tee-times/facility/6803-golden-bear-golf-club-at-indigo-run/search",
  "arthur-hills": "https://www.golfnow.com/tee-times/facility/16425-arthur-hills-at-the-highlands-boyne/search",
  "donald-ross": "https://www.golfnow.com/tee-times/facility/16426-donald-ross-memorial-at-the-highlands-boyne/search",
  "bay-harbor": "https://www.golfnow.com/tee-times/facility/16432-the-linksquarry-at-bay-harbor-golf-club-boyne/search",
  "paiute": "https://www.golfnow.com/tee-times/facility/6332-paiute-golf-resort-wolf/search",
  "monument-boyne": "https://www.golfnow.com/tee-times/facility/16431-the-monument-at-boyne-mountain-resort-boyne/search",
  "dunmaglas": "https://www.golfnow.com/tee-times/facility/4080-dunmaglas-golf-club/search",
  "crooked-tree": "https://www.golfnow.com/tee-times/facility/16427-crooked-tree-golf-club-boyne/search",
  "bali-hai": "https://www.golfnow.com/tee-times/facility/5359-bali-hai-golf-club/search",
  "revere-concord": "https://www.golfnow.com/tee-times/facility/4241-the-revere-golf-club-concord/search",
  "boulder-creek": "https://www.golfnow.com/tee-times/facility/157-boulder-creek-golf-club/search",
  "arroyo-red-rock": "https://www.golfnow.com/tee-times/facility/371-arroyo-golf-club-at-red-rock/search",
  "disney-magnolia": "https://www.golfnow.com/tee-times/facility/3813-disneys-magnolia-golf-course/search",
  "waldorf-astoria": "https://www.golfnow.com/tee-times/facility/4853-waldorf-astoria-golf-club/search",
  "crooked-cat": "https://www.golfnow.com/tee-times/facility/6019-crooked-cat-orange-county-national/search",
  "shingle-creek": "https://www.golfnow.com/tee-times/facility/3606-shingle-creek-golf-club/search",
  "panther-lake": "https://www.golfnow.com/tee-times/facility/552-panther-lake-orange-county-national/search",
  "disney-palm": "https://www.golfnow.com/tee-times/facility/3809-disneys-palm-golf-course/search",
  "aviara": "https://www.golfnow.com/tee-times/facility/4082-aviara-golf-club/search",
  "maderas": "https://www.golfnow.com/tee-times/facility/3069-maderas-golf-club/search",
  "singing-hills": "https://www.golfnow.com/tee-times/facility/3532-singing-hills-golf-club-willow-glen/search",
  "steele-canyon": "https://www.golfnow.com/tee-times/facility/176-steele-canyon-golf-course/search",
  "mt-woodson": "https://www.golfnow.com/tee-times/facility/4078-mt-woodson-golf-club/search",
  'troon-north':
    'https://www.golfnow.com/tee-times/facility/813-troon-north-golf-club/search',
  'tpc-stadium':
    'https://www.golfnow.com/tee-times/facility/3482-the-stadium-course-at-tpc-scottsdale/search',
  'tpc-champions':
    'https://www.golfnow.com/tee-times/facility/7076-tpc-scottsdale-champions-course/search',
  kierland:
    'https://www.golfnow.com/tee-times/facility/80-kierland-golf-club/search',
  mcdowell:
    'https://www.golfnow.com/tee-times/facility/4872-mcdowell-mountain-golf-club/search',
  'tpc-myrtle':
    'https://www.golfnow.com/tee-times/facility/5426-tpc-myrtle-beach/search',
  caledonia:
    'https://www.golfnow.com/tee-times/facility/5415-caledonia-golf-fish-club/search',
  'barefoot-dye':
    'https://www.golfnow.com/tee-times/facility/5348-barefoot-resort-dye/search',
  'kings-north':
    'https://www.golfnow.com/tee-times/facility/5398-myrtle-beach-national-kings-north/search',
  'world-tour':
    'https://www.golfnow.com/tee-times/facility/5413-world-tour-golf-links/search',
  'man-o-war':
    'https://www.golfnow.com/tee-times/facility/5400-man-o-war-golf-course/search',
  arrowhead:
    'https://www.golfnow.com/tee-times/facility/5391-arrowhead-country-club/search',
  'indigo-creek':
    'https://www.golfnow.com/tee-times/facility/5420-indigo-creek-golf-club/search',
}

export interface TripPackage {
  id: string
  destination: string
  region: string
  tier: 'luxury' | 'value'
  tierLabel: string
  title: string
  blurb: string
  image: string
  budgetMin: number
  budgetMax: number
  hotelTier: HotelTier
  needsFlights: boolean
  greenFee: number
  courses: PackageCourse[]
}

// Number of gallery photos downloaded per course (public/packages/<slug>-N.jpg)
const PHOTO_COUNTS: Record<string, number> = {
  "pga-west-stadium": 5,
  "indian-wells-celebrity": 4,
  "desert-willow-firecliff": 4,
  "indian-canyons-north": 4,
  "tahquitz-legend": 6,
  "escena": 3,
  "tiburon-gold": 6,
  "saltleaf": 1,
  "lely-flamingo": 3,
  "eagle-lakes": 6,
  "valencia-naples": 6,
  "cypress-woods": 4,
  "pinehurst-no2": 5,
  "tobacco-road": 2,
  "mid-pines": 1,
  "legacy-golf-links": 5,
  "talamore": 6,
  "longleaf": 3,
  "kiawah-ocean": 2,
  "kiawah-turtle-point": 1,
  "wild-dunes-links": 5,
  "patriots-point": 5,
  "rivertowne": 3,
  "charleston-muni": 4,
  "harbour-town": 10,
  "atlantic-dunes": 4,
  "heron-point": 4,
  "oyster-reef": 5,
  "old-south": 5,
  "golden-bear": 5,
  "arthur-hills": 3,
  "donald-ross": 4,
  "bay-harbor": 4,
  "monument-boyne": 4,
  dunmaglas: 4,
  "crooked-tree": 5,
  "shadow-creek": 5,
  paiute: 5,
  cascata: 7,
  serket: 7,
  "bali-hai": 5,
  "revere-concord": 7,
  "boulder-creek": 6,
  "arroyo-red-rock": 6,
  "disney-magnolia": 7,
  "waldorf-astoria": 8,
  "crooked-cat": 7,
  "shingle-creek": 8,
  "panther-lake": 5,
  "disney-palm": 7,
  aviara: 7,
  maderas: 8,
  "torrey-pines": 7,
  "singing-hills": 6,
  "steele-canyon": 7,
  "mt-woodson": 9,
  wekopa: 8,
  'troon-north': 9,
  'tpc-stadium': 13,
  'tpc-champions': 13,
  kierland: 11,
  mcdowell: 14,
  'tpc-myrtle': 14,
  caledonia: 4,
  'barefoot-dye': 2,
  'kings-north': 12,
  'world-tour': 14,
  'man-o-war': 13,
  arrowhead: 14,
  'indigo-creek': 6,
}

const BASE = import.meta.env.BASE_URL
const imgs = (slug: string): string[] =>
  Array.from(
    { length: PHOTO_COUNTS[slug] ?? 0 },
    (_, i) => `${BASE}packages/${slug}-${i + 1}.jpg`,
  )

function course(name: string, slug: string, blurb: string): PackageCourse {
  return {
    name,
    slug,
    blurb,
    images: imgs(slug),
    golfNow: GOLFNOW[slug],
    website: WEBSITE[slug],
  }
}

const COURSES: Record<string, PackageCourse> = {
  pgaWestStadium: course("PGA West — Pete Dye Stadium Course", "pga-west-stadium", "The valley's most famous course and a former PGA Tour host — Pete Dye's brutal, beautiful stadium design in La Quinta, packed with island greens, deep bunkers, and water."),
  indianWellsCelebrity: course("Indian Wells Golf Resort — Celebrity Course", "indian-wells-celebrity", "A Clive Clark design ranked among the top municipal courses in the U.S., with waterfalls, lakes, and dramatic mountain backdrops."),
  desertWillowFirecliff: course("Desert Willow Golf Resort — Firecliff", "desert-willow-firecliff", "A 7,056-yard Hurdzan/Fry championship layout with more than 100 bunkers and waste areas, ranked among the best you can play in California."),
  indianCanyonsNorth: course("Indian Canyons Golf Resort — North Course", "indian-canyons-north", "A classic William P. Bell parkland layout in the heart of Palm Springs — mature trees, mountain views, and one of the few valley courses you can walk."),
  tahquitzLegend: course("Tahquitz Creek — Legend Course", "tahquitz-legend", "An Arnold Palmer-managed public course with sweeping San Jacinto Mountain views — a well-conditioned, walkable Palm Springs favorite rated among the best places to play."),
  escena: course("Escena Golf Club", "escena", "A 7,211-yard Jack Nicklaus Signature design offering big-course architecture, great mountain views, and a popular clubhouse lounge in Palm Springs."),
  tiburonGold: course("Tiburón Golf Club — Gold Course", "tiburon-gold", "A Greg Norman-designed, Troon-managed championship layout beside the Ritz-Carlton and host of the LPGA CME Group Tour Championship, with coquina waste bunkers and no rough."),
  saltleaf: course("Saltleaf Golf Preserve", "saltleaf", "The former Raptor Bay site reborn as an 18-hole Raymond Floyd design in a coastal village on Estero Bay — Troon-managed and open to the public."),
  lelyFlamingo: course("Lely Resort — Flamingo Island Course", "lely-flamingo", "A Robert Trent Jones-designed 7,171-yard par 72 shaped by water hazards, hourglass fairways, and white-sand bunkers, with Sam Snead's Oak Grill on site."),
  eagleLakes: course("Eagle Lakes Golf Club", "eagle-lakes", "A par-72 championship daily-fee course built around 21 lakes with abundant Everglades wildlife — consistently strong value near Olde Naples."),
  valenciaNaples: course("Valencia Golf & Country Club", "valencia-naples", "A public par 72 stretching to 7,145 yards with wide fairways, contoured greens, and cypress stands — a Naples value staple with frequent daily specials."),
  cypressWoods: course("Cypress Woods Golf & Country Club", "cypress-woods", "An 18-hole, 6,330-yard par 71 open to the public — a friendly, manageable layout ideal for a relaxed group round."),
  pinehurstNo2: course("Pinehurst No. 2", "pinehurst-no2", "Donald Ross's masterpiece and multiple U.S. Open host, defined by turtleback greens and native sandy waste areas — a true bucket-list round at the heart of Pinehurst Resort."),
  tobaccoRoad: course("Tobacco Road Golf Club", "tobacco-road", "Mike Strantz's wild, sand-drenched design carved from an old quarry near Sanford — dramatic, polarizing, and one of the most talked-about public courses in the state."),
  midPines: course("Mid Pines Inn & Golf Club", "mid-pines", "A beautifully restored 1921 Donald Ross gem with rolling fairways and classic contours — walkable, timeless, and a Sandhills favorite."),
  legacyGolfLinks: course("Legacy Golf Links", "legacy-golf-links", "A Jack Nicklaus II design in Aberdeen with generous fairways and a strong finishing stretch — a fun, well-conditioned track with great tee-time deals."),
  talamore: course("Talamore Golf Resort", "talamore", "A Rees Jones layout famous for its llama caddies — a scenic, welcoming test for all levels with a TopTracer range and five sets of tees."),
  longleaf: course("Longleaf Golf & Family Club", "longleaf", "A Dan Maples design with an open front nine and a wooded back, plus new bermuda greens — fair, fun, and very affordable."),
  kiawahOcean: course("The Ocean Course at Kiawah Island", "kiawah-ocean", "Pete Dye's wind-swept seaside masterpiece and host of the 2012 and 2021 PGA Championships, with ten holes hugging the Atlantic — one of the toughest, most scenic courses in America."),
  kiawahTurtlePoint: course("Turtle Point at Kiawah Island", "kiawah-turtle-point", "A Jack Nicklaus design weaving through live oaks and lagoons before three signature holes open onto the ocean — refined and more forgiving than its famous neighbor."),
  wildDunesLinks: course("Wild Dunes Resort — Links Course", "wild-dunes-links", "Tom Fazio's debut design on Isle of Palms, finishing with two dramatic holes along the Atlantic dunes — a classic Lowcountry links just north of Charleston."),
  patriotsPoint: course("Patriots Point Golf Links", "patriots-point", "A harborside layout at the foot of the Ravenel Bridge with sweeping views of Charleston Harbor, Fort Sumter, and the skyline — recently updated and endlessly playable."),
  rivertowne: course("RiverTowne Country Club", "rivertowne", "An Arnold Palmer Signature course threading through marshland and live oaks in Mount Pleasant, with thirteen holes along the Wando River and Horlbeck Creek."),
  charlestonMuni: course("Charleston Municipal Golf Course", "charleston-muni", "A beloved 1929 walkable classic on James Island known as The Muni, minutes from downtown — affordable, historic, and a local favorite."),
  harbourTown: course("Harbour Town Golf Links", "harbour-town", "Pete Dye's iconic Lowcountry links and home of the PGA Tour's RBC Heritage, famed for its tight, oak-lined fairways and the lighthouse-backed 18th."),
  atlanticDunes: course("Atlantic Dunes by Davis Love III", "atlantic-dunes", "A Davis Love III design winding through maritime forest and dunes, blending classic Lowcountry charm with modern, playable shot values."),
  heronPoint: course("Heron Point by Pete Dye", "heron-point", "A Pete Dye layout at Sea Pines with rolling fairways, water, and strategic bunkering set among moss-draped oaks."),
  oysterReef: course("Oyster Reef Golf Club", "oyster-reef", "A Rees Jones design known for its scenic par-3 sixth overlooking Port Royal Sound, with mature trees and generous fairways."),
  oldSouth: course("Old South Golf Links", "old-south", "A scenic public course running from oak-lined parkland to open marshland with classic Lowcountry views."),
  goldenBear: course("Golden Bear Golf Club at Indigo Run", "golden-bear", "A Jack Nicklaus Golden Bear design at Indigo Run with rolling terrain, lagoons, and a relaxed, playable layout."),
  arthurHills: course("Arthur Hills at the Highlands", "arthur-hills", "A rolling, tree-lined mountain course carved through northern Michigan hardwoods with dramatic elevation changes."),
  donaldRoss: course("Donald Ross Memorial", "donald-ross", "A tribute layout where every hole recreates a famous Donald Ross design, showcasing the legendary architect's timeless style."),
  bayHarbor: course("The Links / Quarry at Bay Harbor", "bay-harbor", "An Arthur Hills design on the bluffs of Lake Michigan, where the Links and Quarry nines wind past an old shale quarry and deliver dramatic Great Lakes vistas."),
  monumentBoyne: course("The Monument at Boyne Mountain", "monument-boyne", "A scenic mountaintop course with sweeping views, dramatic elevation, and holes honoring golf's great architects."),
  dunmaglas: course("Dunmaglas Golf Club", "dunmaglas", "A dramatic layout with over 200 feet of elevation change, panoramic vistas, and demanding shot-making through the hills."),
  crookedTree: course("Crooked Tree Golf Club", "crooked-tree", "Overlooking Little Traverse Bay, a links-inspired course with wildflower roughs and stunning water views."),
  shadowCreek: course("Shadow Creek", "shadow-creek", "Tom Fazio's legendary, ultra-exclusive desert oasis — a manufactured wonderland of pines, water, and elevation ranked among America's best."),
  paiute: course("Las Vegas Paiute — Wolf Course", "paiute", "The longest course in Nevada, a Pete Dye desert design with island greens and dramatic mountain backdrops."),
  cascata: course("Cascata", "cascata", "A Rees Jones masterpiece with a 418-foot waterfall and a stream running through the clubhouse, set in a private mountain canyon."),
  serket: course("Serket Golf Club", "serket", "A modern high-desert course with dramatic canyon and plateau holes and sweeping views toward the Strip."),
  baliHai: course("Bali Hai Golf Club", "bali-hai", "A South Seas-themed course beside the Strip with tropical landscaping, water features, and bright white-sand bunkers."),
  revereConcord: course("The Revere — Concord Course", "revere-concord", "Rolling desert fairways with dramatic elevation and panoramic valley and Strip views."),
  boulderCreek: course("Boulder Creek Golf Club", "boulder-creek", "A 27-hole desert facility with mountain backdrops, generous fairways, and excellent conditioning at a great value."),
  arroyoRedRock: course("Arroyo Golf Club at Red Rock", "arroyo-red-rock", "An Arnold Palmer design routed through natural arroyos beneath the towering cliffs of Red Rock Canyon."),
  disneyMagnolia: course("Disney's Magnolia Golf Course", "disney-magnolia", "The longest of Disney's courses and a former PGA Tour host — wide, forgiving, and dotted with over 90 bunkers, including a Mickey-shaped one."),
  waldorfAstoria: course("Waldorf Astoria Golf Club", "waldorf-astoria", "A Rees Jones design winding through cypress and wetlands, a serene luxury-resort layout minutes from the parks."),
  crookedCat: course("Crooked Cat — Orange County National", "crooked-cat", "An open, links-style course with wind-swept fairways and deep bunkering, a longtime PGA Tour Q-School host."),
  shingleCreek: course("Shingle Creek Golf Club", "shingle-creek", "A resort course with an Arnold Palmer redesign threading through oaks and cypress along Shingle Creek."),
  pantherLake: course("Panther Lake — Orange County National", "panther-lake", "A rolling Orange County National course with elevation changes, water, and forest complementing its Crooked Cat sibling."),
  disneyPalm: course("Disney's Palm Golf Course", "disney-palm", "A classic, tree-lined Disney course with water on nearly half its holes and a tough finishing stretch."),
  aviara: course("Aviara Golf Club", "aviara", "An Arnold Palmer design at the Park Hyatt with immaculate conditioning, waterfalls, and native gardens above Batiquitos Lagoon."),
  maderas: course("Maderas Golf Club", "maderas", "A dramatic Johnny Miller and Robert Muir Graves design through canyons, waterfalls, and oak groves north of San Diego."),
  torreyPines: course("Torrey Pines Golf Course", "torrey-pines", "The famed municipal clifftop course above the Pacific, host of the U.S. Open and an annual PGA Tour stop."),
  singingHills: course("Singing Hills — Willow Glen", "singing-hills", "A mature, tree-lined valley course at Sycuan with water and gentle terrain, great for every skill level."),
  steeleCanyon: course("Steele Canyon Golf Club", "steele-canyon", "A Gary Player 27-hole design with dramatic canyon elevation and scenic mountain vistas east of the city."),
  mtWoodson: course("Mt. Woodson Golf Club", "mt-woodson", "A tight, scenic mountain course famous for its granite boulders, a signature cart bridge, and target-golf shot-making."),
  wekopa: course(
    'We-Ko-Pa (Saguaro & Cholla)',
    'wekopa',
    "One of Arizona's premier golf destinations, where championship golf meets the untouched beauty of the Sonoran Desert. With no homes lining the fairways, every hole offers breathtaking mountain views, pristine conditions, and a true desert golf experience.",
  ),
  troon: course(
    'Troon North Golf Club',
    'troon-north',
    'An absolutely breathtaking golf destination, where dramatic desert landscapes, towering granite boulders, and perfectly manicured fairways create an unforgettable round that challenges players of all skill levels.',
  ),
  tpcStadium: course(
    'TPC Scottsdale — Stadium Course',
    'tpc-stadium',
    "Step onto one of golf's most iconic stages, home of the PGA Tour's WM Phoenix Open. Play the same championship layout as the world's best, highlighted by the legendary par-3 16th hole and a thrilling risk-reward finish.",
  ),
  tpcChampions: course(
    'TPC Scottsdale — Champions Course',
    'tpc-champions',
    'A championship-caliber round that blends strategic design with the natural beauty of the Sonoran Desert. More forgiving than its famous Stadium counterpart, it delivers rolling fairways, pristine greens, and stunning McDowell Mountain views.',
  ),
  kierland: course(
    'Kierland Golf Club',
    'kierland',
    'A modern desert golf experience with beautifully manicured fairways, scenic mountain views, and a fun, player-friendly design. Three unique nine-hole layouts and a relaxed resort atmosphere make it a favorite for all skill levels.',
  ),
  mcdowell: course(
    'McDowell Mountain Golf Club',
    'mcdowell',
    "Nestled in the foothills of the McDowell Mountains, one of Scottsdale's best values without sacrificing quality. Known for dramatic elevation changes, panoramic desert views, and well-conditioned fairways that reward smart shot-making.",
  ),
  tpcMyrtle: course(
    'TPC Myrtle Beach',
    'tpc-myrtle',
    "Play where champions have competed on one of South Carolina's premier championship layouts. Designed by Tom Fazio, it features immaculate conditions, strategic bunkering, and holes that reward precision and smart course management.",
  ),
  caledonia: course(
    'Caledonia Golf & Fish Club',
    'caledonia',
    "Consistently ranked among America's finest public courses, Caledonia blends stunning Lowcountry scenery with timeless architecture. Moss-draped oaks, blooming flowers, and unforgettable finishing holes create a beautiful, challenging round.",
  ),
  barefootDye: course(
    'Barefoot Resort — Dye Course',
    'barefoot-dye',
    'Designed by the legendary Pete Dye, this award-winning layout combines dramatic visuals with strategic shot-making. Waste areas, railroad ties, and sculpted bunkers define one of the most unique golf experiences in Myrtle Beach.',
  ),
  kingsNorth: course(
    "Myrtle Beach National — King's North",
    'kings-north',
    'An Arnold Palmer masterpiece renowned for its exciting risk-reward design and iconic holes, including the famous "Gambler" par five. Exceptional conditioning and creative architecture make it one of Myrtle Beach\'s most popular courses.',
  ),
  worldTour: course(
    'World Tour Golf Links',
    'world-tour',
    "Travel the world without leaving Myrtle Beach. Featuring replicas of some of golf's most famous holes from legendary courses across the globe, World Tour offers a unique and entertaining round of iconic designs in one day.",
  ),
  manOWar: course(
    "Man O' War Golf Club",
    'man-o-war',
    "Surrounded by water on nearly every hole, Man O' War delivers a fun, scenic round filled with risk-and-reward opportunities. Generous fairways and beautiful lake views make this a favorite for golfers of all abilities.",
  ),
  arrowhead: course(
    'Arrowhead Country Club',
    'arrowhead',
    'Known for outstanding value and consistently excellent conditions, Arrowhead offers three unique nine-hole layouts with variety, playability, and an enjoyable challenge — quality golf without the premium price.',
  ),
  indigoCreek: course(
    'Indigo Creek Golf Club',
    'indigo-creek',
    'A welcoming layout with rolling fairways, mature trees, and well-placed water hazards. Friendly for all skill levels and known for excellent value — the perfect way to round out a memorable Myrtle Beach trip.',
  ),
}

const PACKAGES_RAW: TripPackage[] = [
  {
    id: "palm-springs-luxury",
    destination: "Palm Springs, CA",
    region: "California",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Coachella Valley Bucket-List Golf",
    blurb: "Three championship desert layouts golfers travel across the country to play, from PGA West to Indian Wells.",
    image: COURSES.pgaWestStadium.images[0],
    budgetMin: 1500,
    budgetMax: 2600,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 200,
    courses: [COURSES.pgaWestStadium, COURSES.indianWellsCelebrity, COURSES.desertWillowFirecliff],
  },
  {
    id: "palm-springs-value",
    destination: "Palm Springs, CA",
    region: "California",
    tier: "value",
    tierLabel: "Value",
    title: "Palm Springs Value Golf",
    blurb: "Well-regarded public desert courses with mountain views, at prices that keep the trip easy.",
    image: COURSES.escena.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 85,
    courses: [COURSES.indianCanyonsNorth, COURSES.tahquitzLegend, COURSES.escena],
  },
  {
    id: "naples-luxury",
    destination: "Naples, FL",
    region: "Florida",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Naples Championship Golf",
    blurb: "Southwest Florida's most acclaimed resort and championship courses, home to PGA and LPGA events.",
    image: COURSES.tiburonGold.images[0],
    budgetMin: 1300,
    budgetMax: 2200,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 185,
    courses: [COURSES.tiburonGold, COURSES.saltleaf, COURSES.lelyFlamingo],
  },
  {
    id: "naples-value",
    destination: "Naples, FL",
    region: "Florida",
    tier: "value",
    tierLabel: "Value",
    title: "Naples Value Golf",
    blurb: "Solid, well-conditioned daily-fee courses that deliver Naples golf without the resort price tag.",
    image: COURSES.eagleLakes.images[0],
    budgetMin: 600,
    budgetMax: 1100,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 65,
    courses: [COURSES.eagleLakes, COURSES.valenciaNaples, COURSES.cypressWoods],
  },
  {
    id: "pinehurst-luxury",
    destination: "Pinehurst, NC",
    region: "North Carolina",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Pinehurst Sandhills Bucket-List",
    blurb: "Legendary Sandhills tracks anchored by Donald Ross's No. 2 at the birthplace of American golf.",
    image: COURSES.pinehurstNo2.images[0],
    budgetMin: 1800,
    budgetMax: 3000,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 300,
    courses: [COURSES.pinehurstNo2, COURSES.tobaccoRoad, COURSES.midPines],
  },
  {
    id: "pinehurst-value",
    destination: "Pinehurst, NC",
    region: "North Carolina",
    tier: "value",
    tierLabel: "Value",
    title: "Pinehurst Value Golf",
    blurb: "Classic Sandhills golf on well-regarded public courses that won't break the bank.",
    image: COURSES.longleaf.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 80,
    courses: [COURSES.legacyGolfLinks, COURSES.talamore, COURSES.longleaf],
  },
  {
    id: "charleston-luxury",
    destination: "Charleston, SC",
    region: "South Carolina",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Kiawah & Charleston Marquee",
    blurb: "Play the ocean-facing championship layouts that put Kiawah and Isle of Palms on the golf map.",
    image: COURSES.wildDunesLinks.images[0],
    budgetMin: 1600,
    budgetMax: 2800,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 250,
    courses: [COURSES.kiawahOcean, COURSES.kiawahTurtlePoint, COURSES.wildDunesLinks],
  },
  {
    id: "charleston-value",
    destination: "Charleston, SC",
    region: "South Carolina",
    tier: "value",
    tierLabel: "Value",
    title: "Charleston Value Golf",
    blurb: "Well-regarded, wallet-friendly public tracks scattered around the historic Charleston metro.",
    image: COURSES.patriotsPoint.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 90,
    courses: [COURSES.patriotsPoint, COURSES.rivertowne, COURSES.charlestonMuni],
  },
  {
    id: "hhi-luxury",
    destination: "Hilton Head Island, SC",
    region: "South Carolina",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Hilton Head Island Legends",
    blurb: "Play the Lowcountry's most celebrated layouts, led by Pete Dye's iconic Harbour Town, amid moss-draped oaks and coastal beauty.",
    image: COURSES.harbourTown.images[0],
    budgetMin: 1600,
    budgetMax: 2600,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 250,
    courses: [COURSES.harbourTown, COURSES.atlanticDunes, COURSES.heronPoint],
  },
  {
    id: "hhi-value",
    destination: "Hilton Head Island, SC",
    region: "South Carolina",
    tier: "value",
    tierLabel: "Value",
    title: "Hilton Head Value Golf",
    blurb: "Enjoy Hilton Head's scenic, well-kept courses at a friendlier price, with marsh views and mature Lowcountry charm.",
    image: COURSES.goldenBear.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 95,
    courses: [COURSES.oysterReef, COURSES.oldSouth, COURSES.goldenBear],
  },
  {
    id: "boyne-luxury",
    destination: "Boyne, MI",
    region: "Michigan",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Boyne Highlands Golf Escape",
    blurb: "Northern Michigan's premier resort golf — rolling, tree-lined mountain courses and a tribute to golf's greatest designs.",
    image: COURSES.arthurHills.images[0],
    budgetMin: 1400,
    budgetMax: 2200,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 150,
    courses: [COURSES.arthurHills, COURSES.donaldRoss, COURSES.bayHarbor],
  },
  {
    id: "boyne-value",
    destination: "Boyne, MI",
    region: "Michigan",
    tier: "value",
    tierLabel: "Value",
    title: "Boyne Mountain Value Trip",
    blurb: "Big-view mountain golf with dramatic elevation across northern Michigan's scenic hills, without the premium price.",
    image: COURSES.dunmaglas.images[0],
    budgetMin: 800,
    budgetMax: 1300,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 95,
    courses: [COURSES.monumentBoyne, COURSES.dunmaglas, COURSES.crookedTree],
  },
  {
    id: "vegas-luxury",
    destination: "Las Vegas, NV",
    region: "Nevada",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Las Vegas Bucket-List Golf",
    blurb: "The Strip's most exclusive layouts — Shadow Creek, Cascata and more — desert masterpieces built without compromise.",
    image: COURSES.cascata.images[0],
    budgetMin: 2500,
    budgetMax: 4500,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 400,
    courses: [COURSES.shadowCreek, COURSES.paiute, COURSES.cascata, COURSES.serket],
  },
  {
    id: "vegas-value",
    destination: "Las Vegas, NV",
    region: "Nevada",
    tier: "value",
    tierLabel: "Value",
    title: "Las Vegas Value Golf",
    blurb: "Dramatic desert golf beneath the mountains and beside the Strip, at prices that keep the trip fun.",
    image: COURSES.baliHai.images[0],
    budgetMin: 700,
    budgetMax: 1300,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 130,
    courses: [COURSES.baliHai, COURSES.revereConcord, COURSES.boulderCreek, COURSES.arroyoRedRock],
  },
  {
    id: "orlando-luxury",
    destination: "Orlando, FL",
    region: "Florida",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "Orlando Championship Golf",
    blurb: "Play Disney's famed layouts and luxury resort designs threading through cypress, wetlands and Central Florida sun.",
    image: COURSES.waldorfAstoria.images[0],
    budgetMin: 1300,
    budgetMax: 2000,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 160,
    courses: [COURSES.disneyMagnolia, COURSES.waldorfAstoria, COURSES.crookedCat],
  },
  {
    id: "orlando-value",
    destination: "Orlando, FL",
    region: "Florida",
    tier: "value",
    tierLabel: "Value",
    title: "Orlando Value Golf Getaway",
    blurb: "Fun, well-kept resort courses across Orlando — Disney and Orange County National — at a wallet-friendly price.",
    image: COURSES.pantherLake.images[0],
    budgetMin: 600,
    budgetMax: 1100,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 85,
    courses: [COURSES.shingleCreek, COURSES.pantherLake, COURSES.disneyPalm],
  },
  {
    id: "sandiego-luxury",
    destination: "San Diego, CA",
    region: "California",
    tier: "luxury",
    tierLabel: "Luxury",
    title: "San Diego Coastal Golf",
    blurb: "From clifftop Torrey Pines to Aviara's gardens, play Southern California's most scenic and celebrated courses.",
    image: COURSES.maderas.images[0],
    budgetMin: 1600,
    budgetMax: 2600,
    hotelTier: "luxury",
    needsFlights: true,
    greenFee: 220,
    courses: [COURSES.aviara, COURSES.maderas, COURSES.torreyPines],
  },
  {
    id: "sandiego-value",
    destination: "San Diego, CA",
    region: "California",
    tier: "value",
    tierLabel: "Value",
    title: "San Diego Value Golf",
    blurb: "Scenic canyon and valley courses across San Diego's backcountry — great golf and mountain views for less.",
    image: COURSES.singingHills.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: "midrange",
    needsFlights: true,
    greenFee: 95,
    courses: [COURSES.singingHills, COURSES.steeleCanyon, COURSES.mtWoodson],
  },
  {
    id: 'scottsdale-luxury',
    destination: 'Scottsdale, AZ',
    region: 'Arizona',
    tier: 'luxury',
    tierLabel: 'Luxury',
    title: 'Scottsdale Bucket-List Golf',
    blurb:
      "Designed for golfers seeking the ultimate Scottsdale experience, this bucket-list package features championship courses, breathtaking desert scenery, and world-class accommodations. Play some of Arizona's most iconic layouts while enjoying a luxury golf getaway you'll never forget.",
    image: COURSES.wekopa.images[0],
    budgetMin: 2200,
    budgetMax: 3500,
    hotelTier: 'luxury',
    needsFlights: true,
    greenFee: 225,
    courses: [COURSES.wekopa, COURSES.troon, COURSES.tpcStadium],
  },
  {
    id: 'scottsdale-value',
    destination: 'Scottsdale, AZ',
    region: 'Arizona',
    tier: 'value',
    tierLabel: 'Value',
    title: 'Scottsdale Value Golf',
    blurb:
      'Offering the perfect balance of quality and value, this package combines outstanding Scottsdale golf with comfortable accommodations at a more affordable price. Enjoy challenging desert layouts, stunning scenery, and an unforgettable getaway without stretching your budget.',
    image: COURSES.mcdowell.images[0],
    budgetMin: 1100,
    budgetMax: 1800,
    hotelTier: 'midrange',
    needsFlights: true,
    greenFee: 110,
    courses: [COURSES.tpcChampions, COURSES.kierland, COURSES.mcdowell],
  },
  {
    id: 'myrtle-luxury',
    destination: 'Myrtle Beach, SC',
    region: 'South Carolina',
    tier: 'luxury',
    tierLabel: 'Luxury',
    title: 'Myrtle Beach Championship Experience',
    blurb:
      'Experience the very best of the "Golf Capital of the World" with a bucket-list getaway featuring some of Myrtle Beach\'s most celebrated courses. From championship layouts to breathtaking Lowcountry scenery, this premium package delivers an unforgettable week of world-class golf.',
    image: COURSES.caledonia.images[0],
    budgetMin: 1400,
    budgetMax: 2200,
    hotelTier: 'luxury',
    needsFlights: true,
    greenFee: 175,
    courses: [
      COURSES.tpcMyrtle,
      COURSES.caledonia,
      COURSES.barefootDye,
      COURSES.kingsNorth,
    ],
  },
  {
    id: 'myrtle-value',
    destination: 'Myrtle Beach, SC',
    region: 'South Carolina',
    tier: 'value',
    tierLabel: 'Value',
    title: 'Myrtle Beach Value Getaway',
    blurb:
      "Discover why Myrtle Beach is one of America's favorite golf destinations with a vacation that won't break the bank. This package combines fun, well-maintained courses with comfortable accommodations — the perfect balance of quality, value, and unforgettable rounds.",
    image: COURSES.worldTour.images[0],
    budgetMin: 700,
    budgetMax: 1200,
    hotelTier: 'midrange',
    needsFlights: true,
    greenFee: 80,
    courses: [
      COURSES.worldTour,
      COURSES.manOWar,
      COURSES.arrowhead,
      COURSES.indigoCreek,
    ],
  },
]

// Show destinations most-popular first; stable sort keeps Luxury before Value.
const DEST_ORDER = [
  'Scottsdale, AZ',
  'Myrtle Beach, SC',
  'Hilton Head Island, SC',
  'Las Vegas, NV',
  'San Diego, CA',
  'Boyne, MI',
  'Orlando, FL',
  'Pinehurst, NC',
  'Palm Springs, CA',
  'Charleston, SC',
  'Naples, FL',
]

export const PACKAGES: TripPackage[] = [...PACKAGES_RAW].sort(
  (a, b) => DEST_ORDER.indexOf(a.destination) - DEST_ORDER.indexOf(b.destination),
)

export function getPackage(id: string): TripPackage | undefined {
  return PACKAGES.find((p) => p.id === id)
}
